sudo: required
language: generic

services:
  - docker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "shopable"
  env: "Shopable-env"
  bucket_name: "elasticbeanstalk-us-east-1-971902593315"
  bucket_path: "shopable"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY